###
POST http://localhost:3001/api/users HTTP/1.1
content-Type: application/json

{
    "name": "testprueba3",
    "email": "sulliTres@test.com",
    "password": "testTres"
}
###
PUT http://localhost:3001/api/users/656327dbe3970b38e7c58ed HTTP/1.1
content-Type: application/json

{
    "name": "Angel",
    "email": "angeltest@test.com",
    "password": "prueba123456"
}

###
GET  http://localhost:3001/api/users HTTP/1.1
content-Type: application/json

###
GET  http://localhost:3001/api/users/6561ecb41dfd57863531fc6b HTTP/1.1
content-Type: application/json

###

GET  http://localhost:3001/api/product HTTP/1.1
content-Type: application/json

###
POST http://localhost:3001/api/product HTTP/1.1
content-Type: application/json

{
    "name": "prueba",
    "description": "descripcion de la chia",
    "price": "25000"
}

###
GET  http://localhost:3001/api/product/656311e28daa0d735bf476b1 HTTP/1.1
content-Type: application/json

###
PUT  http://localhost:3001/api/product/656311e28daa0d735bf476b1 HTTP/1.1
content-Type: application/json

{
    "name": "PRUEBA",
    "description": "descripcion de la pRUEBA",
    "price": "25000"
}