###
POST http://localhost:3001/api/users HTTP/1.1
content-Type: application/json

{
    "name": "testprueba3",
    "email": "sulliTres@test.com",
    "password": "testTres"
}
###
PUT http://localhost:3001/api/users/6564b0bfcaa418ca8e66fd44 HTTP/1.1
content-Type: application/json

{
    "name": "Alejandro",
    "email": "alejandrtest@test.com",
    "password": "prueba123456"
}

###
GET  http://localhost:3001/api/users HTTP/1.1
content-Type: application/json

###
GET  http://localhost:3001/api/users/6564b0bfcaa418ca8e66fd44 HTTP/1.1
content-Type: application/json

###

GET  http://localhost:3001/api/product HTTP/1.1
content-Type: application/json

###
POST http://localhost:3001/api/product HTTP/1.1
content-Type: application/json

{
    "name": "prueba chia",
    "description": "descripcion de la chia",
    "price": "25000"
}

###
GET  http://localhost:3001/api/product/656311e28daa0d735bf476b1 HTTP/1.1
content-Type: application/json

###
PUT  http://localhost:3001/api/product/656311e28daa0d735bf476b1 HTTP/1.1
content-Type: application/json

{
    "name": "PRUEBA",
    "description": "descripcion de la pRUEBA",
    "price": "25000"
}

###

POST http://localhost:3001/api/register HTTP/1.1
content-Type: application/json
{
    "hola": "estamos registrando"
}

###
POST http://localhost:3001/api/register HTTP/1.1
content-Type: application/json
{
  "name": "test14",
  "password": "123456789",
  "email": "test14@email.com"
}